name: Build Firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi make

      - name: Build Firmware
        run: |
          make

      - name: Find and Upload Binary Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pcan_pro_x_g431-firmware
          path: |
            **/*.bin
            **/*.elf
            **/*.hex
